### ISSUE TITLE
Use server-side!!!

### ISSUE THREAD

**Issue by iosdeveloper** [carsonmcdonald/iap-validator#1]
Really, Apple strongly discourages you to validate on device. Instead you should verify against an Apple server server-side.
With this there is no guarantee that the receipt is faked, e.g. using a technique like from this russian hacker, and the user is still able crack your IAP and unlock the feature free of charge.

**Comment by carsonmcdonald** [comment]
Please check out the example in the README of the project. This is a ruby gem that does server side validation.
